Class {
	#name : #DLRootObject,
	#superclass : #DLColumnObject,
	#category : #'Collections-DoubleLinkedList-DancingLinks'
}

{ #category : #accessing }
DLRootObject >> column [
	self shouldNotImplement
]

{ #category : #accessing }
DLRootObject >> down [
	^ nil
]

{ #category : #accessing }
DLRootObject >> name [
	self shouldNotImplement
]

{ #category : #accessing }
DLRootObject >> size [
	self shouldNotImplement 
]

{ #category : #accessing }
DLRootObject >> up [
	^ nil
]
